### ISSUE TITLE
Hi,我正在翻译lodash4-pre的文档

### ISSUE THREAD

**Issue by think2011** [DearMadMan/lodash-zh#3]
我正在慢吞吞的翻译lodash4的文档，在查怎么翻译`lang`这个单词时找到这里，请问我能参考您的翻译吗？

如果可以的话，希望能有机会与您交流，我的QQ号是452125301

P.S：`lang`就是左侧的分类，我打算翻译成`运算`，不知道是否合适。[lodash.think2011.net](http://lodash.think2011.net)

**Comment by magicdawn** [comment]
`lang` 应该是 `language` 语言相关的吧

**Comment by think2011** [comment]
@magicdawn 我想应该不是，因为lang分类下的都是一些对对象的处理，包括复制、判断、转换等。

**Comment by magicdawn** [comment]
![image](https://cloud.githubusercontent.com/assets/4067115/12000131/1123105a-ab0b-11e5-9f0a-6bd9222f6334.png)

**Comment by DearMadMan** [comment]
可以啊  这里翻译的也并不标准 几乎是机器硬译的

**Comment by think2011** [comment]
@DearMadMan 太好了，谢谢😄
